#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Mason
version:      1.22
version_from: lib/HTML/Mason.pm
installdirs:  site
requires:
    Scalar::Util:                  1.01
    Exception::Class:              1.14
    Params::Validate:              0.59
    File::Spec:                    0.8
    CGI:                           2.46
    Apache::Request:               0.32
    Class::Container:              0.07
    Cache::Cache:                  1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_07
